name: Maven Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ '1.8' ]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Prepare Maven project - Java ${{ matrix.java }}
      run: ant -f test.xml build-maven-tests
    - name: Run Maven tests - Java ${{ matrix.java }}
      run: |
        cd build
        mvn test
      env:
        ON_CI: true
